SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `laravel` DEFAULT CHARACTER SET latin1 ;
USE `laravel` ;

-- -----------------------------------------------------
-- Table `laravel`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`users` ;

CREATE  TABLE IF NOT EXISTS `laravel`.`users` (
  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `USER_NAME` VARCHAR(45) NOT NULL ,
  `FNAME` VARCHAR(45) NOT NULL ,
  `LNAME` VARCHAR(45) NOT NULL ,
  `EMAIL` VARCHAR(45) NOT NULL ,
  `PHONE` VARCHAR(45) NOT NULL ,
  `PASSWORD` VARCHAR(45) NOT NULL ,
  `STREET` VARCHAR(45) NOT NULL ,
  `STATE` VARCHAR(45) NOT NULL ,
  `ZIP` INT(11) NOT NULL ,
  PRIMARY KEY (`USER_ID`) ,
  UNIQUE INDEX `USER_NAME_UNIQUE` (`USER_NAME` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;

USE `laravel` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
